### PR TITLE
Fb pdb

### PR DESCRIPTION
**Pull request by pdred**
Fixed the PDB gold tier common microservices to use the correct namespace

### CODE REVIEW

**Comment by pdred** [comment]
Higher ranking pull request required for the new shop operator.

**Comment by pdred** [comment]
Missing the pdb deployment in the createnamespace.sh script. Closing this version of the pr.

**Comment by pdred** [comment]
There are 8 commits that took place after this code was submitted. Will reopen the request once the code has been validated.

**Comment by pdred** [comment]
Pulled in the current main branch and all tests completed without issue. Will redo the tests once @sauagarwa approves Jude's HPA pr.

**Review by sauagarwa — APPROVED** [review]

**Pull request merged**
